const path=[{
    name:"copy",
    image:"./images/copy.png"
},
{
    name:"delete",
    image:"./images/delete.png"
},
{
    name:"eraser",
    image:"./images/eraser.png"
},
{
    name:"file",
    image:"./images/file.png"
},
{
    name:"logo",
    image:"./images/logo.png"
},
{
    name:"lowercase",
    image:"./images/lowercase.png"
},
{
    name:"uppercase",
    image:"./images/uppercase.png"
},
]
export default path